services:
  mysql:
    image: mysql:latest
    container_name: TrabajoYML
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "BibliotecaP"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3310:3306"
    volumes:
      - "mysql_db:/var/lib/mysql"
      - ./inicio.sql:/docker-entrypoint-initdb.d/inicio.sql

volumes:
  mysql_db: